/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DonHang;

import MenuQuanLy.MenuForm;
import NhanVien.NhanVien;
import NhanVien.TTNVForm;
import SanPham.SanPham;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLyDHForm extends javax.swing.JFrame {

    private ArrayList<DonHang> listDH = DonHang.getDonHangList();
    private ArrayList<SanPham> listSP = SanPham.getSanPhamList();
    private ArrayList<NhanVien> listNV = NhanVien.getNhanVienList();
    private DefaultTableModel tblModel = new DefaultTableModel();

    /**
     * Creates new form QLyDHForm
     */
    public QLyDHForm() {
        initComponents();
        initTable();
        fillTable();
        setLocationRelativeTo(null); // chinh cua so xuat hien chinh giua man hinh
    }

    private int tongMaNV(String MaNV) {
        int countMaNV = 0;
        for (NhanVien nv : listNV) {
            if (!nv.getMaNV().equalsIgnoreCase(txtMaNV.getText())) {
                countMaNV += 1;
            }
        }
        return countMaNV;
    }

    private int tongMaSP(String MaSP) {
        int countMaSP = 0;
        for (SanPham sp : listSP) {
            if (!sp.getMaSP().equalsIgnoreCase(txtMaSP.getText())) {
                countMaSP += 1;
            }
        }
        return countMaSP;
    }

    private double tinhTienTheoMaSP(String maSP) {
        for (SanPham o : listSP) {
            if (o.getMaSP().equalsIgnoreCase(maSP)) {
                return o.getGia();
            }
        }
        return 0;
    }

    private boolean dieukienSL(String SLM) {
        String text = txtSLM.getText();
        try {
            int value = Integer.parseInt(text);
            if (value < 0) {
                return false;
            }
        } catch (NumberFormatException ex) {
            return false;
        }
        return true;
    }

    private void fillTable() {
        tblModel.setRowCount(0);
        for (DonHang o : listDH) {
            tblModel.addRow(new String[]{o.getMaDH(), o.getMaSP(), o.getMaNV(),
                "" + o.getSoLuongMua(), o.getNgay(),
                "" + (o.getSoLuongMua() * tinhTienTheoMaSP(o.getMaSP()))});
        }

        tblModel.fireTableDataChanged();
    }

    private void initTable() {
        String[] columns = new String[]{"Mã đơn hàng", "Mã Sản Phẩm", "Mã nhân viên", "Số lượng mua", "Ngày đặt", "TổngTiền"};
        tblModel.setColumnIdentifiers(columns);
        tblDH.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDH = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtSLM = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        btnTTNV = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_xuatFileExcel = new javax.swing.JButton();
        btn_timKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Quản lý đơn hàng");

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Quay Lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        tblDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDH);

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("Thêm mới");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Xóa hết");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng mua: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày đặt hàng: ");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSLM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMaSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTTNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTTNV.setText("Xem thông tin nhân viên tạo đơn hàng");
        btnTTNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTNVActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã Đơn hàng: ");

        txtMaDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDHActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_xuatFileExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xuatFileExcel.setText("Xuất File Excel");
        btn_xuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatFileExcelActionPerformed(evt);
            }
        });

        btn_timKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_timKiem.setText("Tìm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(btnTTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel19)))
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaNV)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(txtMaDH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSLM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_xuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaDH)
                        .addGap(5, 5, 5)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSLM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(btn_xuatFileExcel)
                    .addComponent(btn_timKiem))
                .addGap(22, 22, 22)
                .addComponent(btnTTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MenuForm menuform = new MenuForm();
        menuform.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTTNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTNVActionPerformed
        int SelectedRow = tblDH.getSelectedRow();
        boolean flag = false;
        if (SelectedRow >= 0) 
        {
            String maNV = (String) tblDH.getValueAt(SelectedRow, 2);
            for (NhanVien nv : listNV) {
                if (maNV.equalsIgnoreCase(nv.getMaNV())) {
                    flag = true;
                    break;
                }
            }
            if (flag) {
                TTNVForm formTTNV = new TTNVForm(maNV);
                formTTNV.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Không có thông tin nhân viên này", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTTNVActionPerformed

    private void tblDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDHMouseClicked
        int SelectedRow = tblDH.getSelectedRow();
        if (SelectedRow >= 0) {
            String maDH = (String) tblDH.getValueAt(SelectedRow, 0);
            for (DonHang dh : listDH) {
                if (maDH.equals(dh.getMaDH())) {
                    txtMaDH.setText(dh.getMaDH());
                    txtMaSP.setText(dh.getMaSP());
                    txtMaNV.setText(dh.getMaNV());
                    txtSLM.setText("" + dh.getSoLuongMua());
                    txtNgay.setText(dh.getNgay());
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblDHMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtMaDH.setText("");
        txtMaSP.setText("");
        txtMaNV.setText("");
        txtSLM.setText("");
        txtNgay.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        StringBuilder sb = new StringBuilder();

        if (txtMaDH.getText().equals("")) {
            sb.append("Mã đơn hàng không được để trống \n");
            txtMaDH.setBackground(Color.gray);
        } else {
            txtMaDH.setBackground(Color.white);
        }
        if (txtMaSP.getText().equals("")) {
            sb.append("Mã Sản Phẩm không được để trống \n");
            txtMaSP.setBackground(Color.gray);
        } else {
            txtMaSP.setBackground(Color.white);
        }
        if (txtMaNV.getText().equals("")) {
            sb.append("Mã nhân viên không được để trống \n");
            txtMaNV.setBackground(Color.gray);
        } else {
            txtMaNV.setBackground(Color.white);
        }

        if (txtSLM.getText().equals("")) {
            sb.append("Số lượng mua không được để trống \n");
            txtSLM.setBackground(Color.gray);
        } else {
            txtSLM.setBackground(Color.white);
        }

        if (txtNgay.getText().equals("")) {
            sb.append("Ngày không được để trống \n");
            txtNgay.setBackground(Color.gray);
        } else {
            txtNgay.setBackground(Color.white);
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int flag = -1;
        for (DonHang o : listDH) {
            if (o.getMaDH().equalsIgnoreCase(txtMaDH.getText())) {
                flag = 0;
                break;
            } else if (tongMaNV(txtMaNV.getText()) == listNV.size()) {
                flag = 1;
                break;
            } else if (tongMaSP(txtMaSP.getText()) == listSP.size()) {
                flag = 2;
            } else if (!dieukienSL(txtSLM.getText()) ) {
                flag = 3;
            }
        }

        if (flag == -1) {
            DonHang a = new DonHang();
            a.setMaDH(txtMaDH.getText());
            a.setMaSP(txtMaSP.getText());
            a.setMaNV(txtMaNV.getText());
            a.setSoLuongMua(Integer.parseInt(txtSLM.getText()));
            a.setNgay(txtNgay.getText());

            listDH.add(a);
            fillTable();

            try {
                FileWriter fw = new FileWriter("CSDL\\DonHang.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(a.toString());
                bw.newLine();
                bw.close();
                fw.close();
            } catch (IOException e) {
            }
        } else if (flag == 0) {
            JOptionPane.showMessageDialog(null, "Đã tồn tại mã đơn hàng này");
        } else if (flag == 1) {
            JOptionPane.showMessageDialog(null, "Mã nhân viên này không hợp lệ ( mã nhân viên phải trùng với các mã nhân viên đã có )");
        } else if (flag == 2) {
            JOptionPane.showMessageDialog(null, "Mã sản phẩm này không hợp lệ ( mã sản phẩm phải trùng với các mã sản phẩm đã có )");
        } else if (flag == 3) {
            JOptionPane.showMessageDialog(null, "Số lượng mua phải là số dương");
        }
        btnClearActionPerformed(evt);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        StringBuilder sb = new StringBuilder();

        if (txtMaDH.getText().equals("")) {
            sb.append("Mã Đơn hàng không được để trống \n");
            txtMaDH.setBackground(Color.gray);
        } else {
            txtMaDH.setBackground(Color.white);
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá đơn hàng không? ", "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }

        // neu chon khong thi tu doan nay se khong thuc hien
        for (DonHang o : listDH) {
            if (o.getMaDH().equalsIgnoreCase(txtMaDH.getText())) {
                listDH.remove(o);
                break;
            }
        }
        // ghi lai file sau khi xoa san pham
        try {
            FileWriter fw = new FileWriter("CSDL\\DonHang.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            for (DonHang o : listDH) {
                bw.write(o.toString());
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException e) {
        }
        fillTable();
        btnClearActionPerformed(evt);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtMaDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDHActionPerformed

    private void btn_xuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatFileExcelActionPerformed
        // TODO add your handling code here:
        ExportExcel.ExportExcel.exportExcel(tblDH);
    }//GEN-LAST:event_btn_xuatFileExcelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();

        if (txtMaSP.getText().equals("")) {
            sb.append("Mã sản phẩm không được để trống \n");
            txtMaSP.setBackground(Color.gray);
        } else {
            txtMaSP.setBackground(Color.white);
        }

        if (txtMaDH.getText().equals("")) {
            sb.append("Mã đơn hàng không được để trống \n");
            txtMaDH.setBackground(Color.gray);
        } else {
            txtMaDH.setBackground(Color.white);
        }

        if (txtMaNV.getText().equals("")) {
            sb.append("Mã nhân viên không được để trống \n");
            txtMaNV.setBackground(Color.gray);
        } else {
            txtMaNV.setBackground(Color.white);
        }

        if (txtSLM.getText().equals("")) {
            sb.append("Số lượng mua không được để trống \n");
            txtSLM.setBackground(Color.gray);
        } else {
            txtSLM.setBackground(Color.white);
        }

        if (txtNgay.getText().equals("")) {
            sb.append("Ngày đặt hàng không được để trống \n");
            txtNgay.setBackground(Color.gray);
        } else {
            txtNgay.setBackground(Color.white);
        }

        

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật thông tin không? ", "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }

        // neu chon khong thi tu doan nay se khong thuc hien
        for (DonHang dh : listDH) {
            if (dh.getMaSP().equals(txtMaSP.getText())) {
                dh.setMaDH(txtMaDH.getText());
                dh.setMaNV(txtMaNV.getText());
                dh.setNgay(txtNgay.getText());
                dh.setSoLuongMua(Integer.parseInt(txtSLM.getText()));
               
                // ghi phan tu sua doi vao file
                try {
                    // mo file database
                    BufferedReader reader = new BufferedReader(new FileReader("CSDL\\DonHang.txt"));
                    // tao 1 mang de luu cac doi tuong trong database
                    ArrayList<String> lines = new ArrayList<>();
                    String line;
                    while ((line = reader.readLine()) != null) {
                        lines.add(line);
                    }
                    // sua phan tu can thay doi
                    for (int i = 0; i < lines.size(); i++) {
                        String[] parts = lines.get(i).split(",");
                        if (parts[0].equalsIgnoreCase(txtMaSP.getText())) {
                            parts[1] = txtMaDH.getText();
                            parts[2] = txtMaNV.getText();
                            parts[3] = txtSLM.getText();
                            parts[4] = txtNgay.getText();
                            String newLine = String.join(",", parts);
                            lines.set(i, newLine);
                            break; // thoat sau khi sua
                        }
                    }
                    // tao doi tuong de ghi lai vao database
                    BufferedWriter writer = new BufferedWriter(new FileWriter("CSDL\\DonHang.txt"));
                    for (String newLine : lines) {
                        writer.write(newLine);
                        writer.newLine();
                    }
                    reader.close();
                    writer.close();
                } catch (IOException e) {
                }

                break;
            }
        }

        fillTable();
        btnClearActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        if(txtMaDH.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập mã đơn hàng");
        }else
        {
            //Xóa bảng
            int rowCount = tblDH.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
                tblModel.removeRow(i);
            }
            for (DonHang dh:listDH)
            {
                if(txtMaDH.getText().equals(dh.getMaDH()))
                {
                    Object[] rowData = {dh.getMaDH()
                            ,dh.getMaSP()
                            ,dh.getMaNV()
                            ,dh.getSoLuongMua()
                            ,dh.getNgay()
                            ,dh.getSoLuongMua()*tinhTienTheoMaSP(dh.getMaSP())};
                    tblModel.addRow(rowData);
                    break;
                }
            }
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLyDHForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLyDHForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLyDHForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLyDHForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLyDHForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTTNV;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xuatFileExcel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblDH;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtSLM;
    // End of variables declaration//GEN-END:variables
}
